#!/bin/bash

# To update the version shipped in this quickstart, bump this variable:
#
install_version="3.8.1"


# Download and install Wordpress

install_dir=${OPENSHIFT_DATA_DIR}${install_version}
mkdir -p ${install_dir}

pushd ${install_dir} >/dev/null
curl -s http://wordpress.org/wordpress-${install_version}.tar.gz | tar --strip-components=1 -xzf -
popd >/dev/null

ln -sf ${install_dir} ${OPENSHIFT_DATA_DIR}current
