#!/bin/bash

# To update the version shipped in this quickstart, bump this variable:
#
install_version="3.8.1"

# Download and install Wordpress

install_dir=${OPENSHIFT_DATA_DIR}${install_version}

# The Wordpress is already installed, nothing else to do...
[ -d "${install_dir}" ] && exit 0

mkdir -p ${install_dir}

pushd ${install_dir} >/dev/null
curl -s http://wordpress.org/wordpress-${install_version}.tar.gz > wordpress-${install_version}.tar.gz

# Verify the sources
#
tarball_md5=$(md5sum wordpress-${install_version}.tar.gz | cut -d ' ' -f 1)
wordpress_md5=$(curl -s http://wordpress.org/wordpress-${install_version}.tar.gz.md5)

if [ "${tarball_md5}" != "${wordpress_md5}" ]; then
  echo "ERROR: Wordpress ${install_version} MD5 checksum mismatch."
  exit 1;
fi

# Install Wordpress
#
tar --strip-components=1 -xzf wordpress-${install_version}.tar.gz
rm -rf wordpress-${install_version}.tar.gz

popd >/dev/null

ln -sf ${install_dir} ${OPENSHIFT_DATA_DIR}current

# Make it easier for users to pass the Wordpress initial setup
# by prefilling the default values to match with OpenShift environment
# variables.
#
sed -i "s/value=\"localhost\"/value=\"${OPENSHIFT_MYSQL_DB_HOST}\"/" ${OPENSHIFT_DATA_DIR}current/wp-admin/setup-config.php
sed -i "s/value=\"wordpress\"/value=\"${OPENSHIFT_APP_NAME}\"/" ${OPENSHIFT_DATA_DIR}current/wp-admin/setup-config.php
sed -i "s/'username'/'${OPENSHIFT_MYSQL_DB_USERNAME}'/" ${OPENSHIFT_DATA_DIR}current/wp-admin/setup-config.php
sed -i "s/'password'/'${OPENSHIFT_MYSQL_DB_PASSWORD}'/" ${OPENSHIFT_DATA_DIR}current/wp-admin/setup-config.php
