#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

set -e

# Replace this with the WordPress administrator's email (or your email).
WP_ADMIN_EMAIL="admin@nobody.com"


function generate_random_password() {
   # Generate a random password without 'em confusing Os and 0s.
   vchars="a-np-zA-NP-Z1-9-_"
   head -n 1024 /dev/urandom | tr -dc "$vchars" | fold -w 16 |  head -n 1
}


if [ -z "$OPENSHIFT_DB_HOST" ]
then
    echo 1>&2
    echo "Could not find mysql database.  Please run:" 1>&2
    echo "rhc app cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.1" 1>&2
    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
    echo 1>&2
fi

RETRY=60
while [ $RETRY -gt 0 ] ; do
    #reload env variables
    for env_var in  $OPENSHIFT_HOMEDIR/.env/*
    do
        . $env_var
    done

    #check for db
    if [ -n "$OPENSHIFT_DB_HOST" ]
    then
        echo "Database server found at $OPENSHIFT_DB_HOST. initializing..."
        sleep 5
        break
    fi

    sleep 1
    RETRY=$(( $RETRY - 1 ))
done

if [ -z "$OPENSHIFT_DB_HOST" ]
then
    exit 5
fi

# Confirm database exists, if not create it
if ! /usr/bin/mysql -h "$OPENSHIFT_DB_HOST" -u "$OPENSHIFT_DB_USERNAME"      \
      --password="$OPENSHIFT_DB_PASSWORD" -e "select * from wp_commentmeta;" \
      "$OPENSHIFT_APP_NAME" > /dev/null 2>&1; then
    echo
    echo "Database schema not found, importing 'wordpress.sql' schema."
    echo

    wp_admin_pass=$(generate_random_password)
    substitutes="s#wordpress-dbvs.rhcloud.com#$OPENSHIFT_APP_DNS#g;  \
                 s#%WP_ADMIN_PASSWORD%#$wp_admin_pass#g;"
    if [ "$WP_ADMIN_EMAIL" != "admin@nobody.com" ]; then
        substitutes="$substitutes s#admin@nobody.com#$WP_ADMIN_EMAIL#g;"
    fi

    cat "$OPENSHIFT_REPO_DIR/.openshift/action_hooks/wordpress.sql"  |      \
        sed "$substitutes"                                           |      \
        /usr/bin/mysql -h "$OPENSHIFT_DB_HOST" -u "$OPENSHIFT_DB_USERNAME"  \
              --password="$OPENSHIFT_DB_PASSWORD" "$OPENSHIFT_APP_NAME"

    echo
    echo "done."
    echo "=================================================="
    echo "     Wordpress-Admin login: admin"
    echo "  Wordpress-Admin password: $wp_admin_pass"
    echo "     Wordpress-Admin email: $WP_ADMIN_EMAIL"
    echo "=================================================="
else
    echo "Database found, skipping import."
fi

$OPENSHIFT_GEAR_CTL_SCRIPT stop
$OPENSHIFT_GEAR_CTL_SCRIPT start
